# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField(blank=True)),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('1', 'Mantenimiento'), ('2', 'Infraestructura')], default='1', max_length=1)),
                ('descripcion', models.TextField(blank=True, max_length=200)),
                ('direccion', models.TextField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('1', 'Ejecutando'), ('2', 'Terminado')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('duracion', models.TimeField(null=True)),
                ('estado', models.CharField(choices=[('1', 'Ejecutando'), ('2', 'Terminado')], default='1', max_length=1)),
            ],
        ),
    ]
