# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='tareas',
            field=models.ManyToManyField(related_query_name='tareas', to='casos.Tarea'),
        ),
    ]
