# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_caso_tareas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='duracion',
            field=models.IntegerField(null=True),
        ),
    ]
