# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('parentesco', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=80)),
                ('apellido', models.CharField(blank=True, max_length=80)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(choices=[('1', 'Albañil'), ('2', 'Maestro de obra')], default='1', max_length=1)),
                ('cuadrilla', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cuadrillas.Cuadrilla')),
            ],
        ),
        migrations.AddField(
            model_name='familiares',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuadrillas.Integrante'),
        ),
    ]
