# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='cuadrilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadrillas.Cuadrilla'),
        ),
    ]
