# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0002_auto_20171017_0354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiares',
            new_name='Familiar',
        ),
    ]
